name: key_value_storage_manager
description: A platform-independent module to manage key-value storage operations for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Key-value storage
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules

