name: flutter_advanced_template_v2
repository: https://github.com/bahricanyesil/flutter-advanced-template-v2

packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*
  - packages/*/packages/*
  - packages/**/example

command:
  version:
    linkToCommits: true
    workspaceChangelog: false
  bootstrap:
    hooks:
      post: melos run format

scripts:
  format: |
    melos exec --concurrency=1 --fail-fast -- "
      dart format --set-exit-if-changed --line-length 80 .
    "

  analyze: |
    melos exec --concurrency=1 --fail-fast -- "
      dart analyze --fatal-infos --fatal-warnings .
    "

  format-analyze: |
    melos run format && melos run analyze

  test: >
    melos run test:dart &&
    melos run test:flutter
  test:dart: >
    melos exec --no-flutter --concurrency=1 --fail-fast --dir-exists=test -- "
      dart test --coverage=coverage &&
      dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage
    "
  test:flutter: melos exec --flutter --concurrency=1 --fail-fast --dir-exists=test -- flutter test --coverage

  open-coverage: |
    melos exec --dir-exists=coverage -- "
      genhtml ./coverage/lcov.info -o coverage &&
      open coverage/index.html
    "

  generate: |
    melos exec --depends-on=build_runner -- "dart run build_runner build -d"
