name: flutter_advanced_template_v2
repository: https://github.com/bahricanyesil/flutter-advanced-template-v2

packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*

command:
  version:
    linkToCommits: true
    workspaceChangelog: false

scripts:
  format: |
    dart format --set-exit-if-changed --line-length 80 packages/

  analyze: |
    # Ensure Dart SDK and packages are up-to-date
    echo "Updating Dart SDK and packages..."
    flutter pub get

    # Run Dart analysis with detailed output
    echo "Analyzing Dart files in the packages directory:"
    dart analyze --fatal-infos --fatal-warnings packages/

  format-analyze: |
    melos run format && melos run analyze

  test: |
    very_good test -r --test-randomize-ordering-seed random --coverage

  open-coverage: |
    original_dir=$(pwd)
    for dir in packages/*/coverage; do \
      if [ -f "$dir/lcov.info" ]; then \
        parent_dir=$(dirname "$dir"); \
        echo "Processing $parent_dir"; \
        cd "$parent_dir"; \
        mkdir -p coverage/html; \
        genhtml ./coverage/lcov.info -o coverage && open coverage/index.html; \
        cd "$original_dir"; \
      else \
        echo "No lcov.info found in $dir"; \
      fi; \
    done

  test-coverage: |
    melos run test
    echo "Tests completed. Opening coverage reports..."
    melos run open-coverage