name: flutter_advanced_template_v2
repository: https://github.com/bahricanyesil/flutter-advanced-template-v2

packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*

command:
  version:
    linkToCommits: true
    workspaceChangelog: false

scripts:
  format: |
    dart format --set-exit-if-changed --line-length 80 packages/

  analyze: |
    # Ensure Dart SDK and packages are up-to-date
    echo "Updating Dart SDK and packages..."
    flutter pub get

    # Run Dart analysis with detailed output
    echo "Analyzing Dart files in the packages directory:"
    dart analyze --fatal-infos --fatal-warnings packages/

  format-analyze: |
    melos run format && melos run analyze

  test: |
    very_good test -r --test-randomize-ordering-seed random --coverage

  open-coverage: |
    for dir in packages/*/; do
      if [ -f "$dir/coverage/index.html" ]; then
        if command -v xdg-open &> /dev/null; then
          xdg-open "$dir/coverage/index.html"
        elif command -v open &> /dev/null; then
          open "$dir/coverage/index.html"
        elif command -v start &> /dev/null; then
          start "$dir/coverage/index.html"
        else
          echo "No suitable command found to open coverage reports"
        fi
      fi
    done
  test-open-coverage: |
    melos run test && melos run open-coverage