name: flutter_advanced_template_v2
packages:
  - packages/analytics_manager
  - packages/connectivity_manager
  - packages/device_info_manager
  - packages/exception_report_manager
  - packages/file_picker
  - packages/image_picker
  - packages/package_info_manager
  - packages/firebase_manager
  - packages/in_app_review_manager
  - packages/localization_manager
  - packages/logger_manager
  - packages/theme_manager
  - packages/navigation_manager
  - packages/network_manager
  - packages/local_notifications_manager
  - packages/push_notifications_manager
  - packages/permission_manager
  - packages/basic_storage_manager
  - packages/cache_storage_manager
  - packages/db_manager
  - packages/secure_storage_manager
scripts:
  test: |
    very_good test -r --test-randomize-ordering-seed random --coverage
  open-coverage: |
    for dir in packages/*/; do
      if [ -f "$dir/coverage/index.html" ]; then
        if command -v xdg-open &> /dev/null; then
          xdg-open "$dir/coverage/index.html"
        elif command -v open &> /dev/null; then
          open "$dir/coverage/index.html"
        elif command -v start &> /dev/null; then
          start "$dir/coverage/index.html"
        else
          echo "No suitable command found to open coverage reports"
        fi
      fi
    done
  test-and-coverage: |
    melos run test && melos run open-coverage