name: cloud_database_manager
description: A platform-independent module to manage cloud-based database operations for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Firestore
  cloud_firestore: ^5.4.0

  # Logging
  log_manager:
    path: ../log_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4

  # Fake Firestore for testing
  fake_cloud_firestore: ^3.0.2
  mock_exceptions: ^0.8.2

