blank_issues_enabled: false
contact_links:
  - name: Flutter Advanced Template v2 Readme
    url: https://github.com/bahricanyesil/flutter-advanced-template-v2/README.md
    about: You can see the details of the repository here.
