name: theme_manager
description: A module to manage themes for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Models
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6

  # Logging
  log_manager:
    path: ../log_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4
