name: push_notification_manager
description: A module to manage push notifications for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Push Notification Packages
  firebase_messaging: ^15.1.3

  # # Permission Manager
  # permission_manager:
  #   path: ../permission_manager

  # Log Manager
  log_manager:
    path: ../log_manager

  # Key Value Storage
  key_value_storage_manager:
    path: ../key_value_storage_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4
