name: language_manager
description: A module to manage languages for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0

  # Logging
  log_manager:
    path: ../log_manager

  # Key-value storage
  key_value_storage_manager:
    path: ../key_value_storage_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4
