name: analytics_manager
description: A module to manage analytics services for Flutter apps.
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  log_manager:
    path: ../log_manager
  mockito: ^5.4.4
