name: Common Checks

on:
  workflow_call:
    secrets:
      ssh_key:
        required: false

jobs:
  license-check:
    uses: ./.github/workflows/license_check.yaml

  decode-github-secrets:
    secrets: inherit
    uses: ./.github/workflows/decode_github_secrets.yaml

  cache:
    needs:
      - decode-github-secrets
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/cache.yaml
    with:
      cache_key: ${{ matrix.os }}-flutter
      cache_path: ~/.pub-cache

  test-and-analysis:
    uses: ./.github/workflows/test_and_analysis.yaml
    secrets: inherit
    needs:
      - license-check
      - cache