name: CI Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  pull-requests: read

jobs:
  pr-checks:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/pr_checks.yaml

  push-checks:
    if: github.event_name == 'push'
    uses: ./.github/workflows/push_checks.yaml

  common-checks:
    uses: ./.github/workflows/common_checks.yaml
    secrets: inherit